### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by slyness** [sparkleformation/sfn#145]
Updating a stack fails

`sfn update mystack`

```
ERROR: NoMethodError: undefined method `fetch' for nil:NilClass
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/planner/aws.rb:360:in `register_diff'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/planner/aws.rb:305:in `block in run_stack_diff'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/planner/aws.rb:304:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/planner/aws.rb:304:in `run_stack_diff'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/planner/aws.rb:193:in `plan_stack'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/planner/aws.rb:135:in `generate_plan'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/lib/sfn/command/update.rb:121:in `execute!'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/bin/sfn:48:in `block (4 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/gems/bogo-cli-0.2.2/lib/bogo-cli/setup.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/bogo-cli-0.2.2/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/usr/local/rvm/gems/ruby-2.2.3/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/rvm/gems/ruby-2.2.3/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/usr/local/rvm/gems/ruby-2.2.3/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/rvm/gems/ruby-2.2.3/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/usr/local/rvm/gems/ruby-2.2.3/gems/bogo-cli-0.2.2/lib/bogo-cli/setup.rb:48:in `define'
/usr/local/rvm/gems/ruby-2.2.3/gems/sfn-2.1.4/bin/sfn:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/bin/sfn:23:in `load'
/usr/local/rvm/gems/ruby-2.2.3/bin/sfn:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by chrisroberts** [comment]
Fixed and released
