### ISSUE TITLE
support .sfn.rb

### ISSUE THREAD

**Issue by grosser** [sparkleformation/sfn#168]
- better hightlighting in most editors
 - no more guessing by bogo what format the file is -> no more swallowing of exceptions when .sfn is not a json file

@chrisroberts

**Comment by grosser** [comment]
FYI monkeypatch

```Ruby
Bogo::Config.prepend(Module.new do
  [:json_load, :yaml_load, :xml_load].each do |loader|
    define_method loader do |file|
      super(file) unless file.end_with?("/.sfn")
    end
  end
end)
```

**Comment by chrisroberts** [comment]
As of 2.2 all supported config format extensions are now supported as well as the default extensionless file.

**Comment by grosser** [comment]
:heart:

**Comment by grosser** [comment]
backtraces are still not showing the original error ...

```
# .sfn.rb
raise "HELOOO"

sfn print -f test_templates/testautoscale.rb
ERROR: Failed to load configuration from file (/Users/mgrosser/Code/zendesk/podzilla/pod/.sfn.rb) - undefined method `to_smash' for "raise \"HELLOOO\"":String

DEBUG=1 sfn print -f test_templates/testautoscale.rb
Stacktrace: NoMethodError: undefined method `to_smash' for "raise \"HELLOOO\"":String
/Users/mgrosser/Code/zendesk/podzilla/vendor/bundle/gems/bogo-config-0.2.0/lib/bogo-config/config.rb:234:in `yaml_load'
... nothing pointing to .sfn.rb ...

BOGO_DEBUG=1 be sfn print -f test_templates/testautoscale.rb
RuntimeError: HELLOOO
.sfn.rb:1:in `struct_load'
... and errors from the 4 other loaders ...
```

bug is in bogo-config-0.2.0/lib/bogo-config/config.rb:206 ... 

`when '.rb' && eval_enabled?` which evaluates to `when true` -> no tests for this code :(
-> fix in https://github.com/spox/bogo-config/pull/5
