### ISSUE TITLE
ERROR: Miasma::Error::ApiError::RequestError: Moved Permanently

### ISSUE THREAD

**Issue by ls-yann-david** [sparkleformation/sfn#182]
For some reason, I tried to pinpoint this to some code change but no matter from which commit I try to run my sfn update command, I get this error. Any idea why ? Did something change for stack updates that I missed?

**Comment by chrisroberts** [comment]
Hi! Are you using AWS as the provider? Is your stack utilizing nesting?

**Comment by ls-yann-david** [comment]
Yes I'm using AWS and yes I'm using nesting

Here's the actually full run (Sanitized)

```bash
⇒  sfn update logstash-development -f sparkleformation/templates/logstash/standalone.rb --nesting-bucket sfn-dev
[Sfn]: Stack runtime parameters: - template: logstash-development > LogstashCacheCluster
[Sfn]: Env Product [XXXX]:
[Sfn]: Env Name [XXXX]:
[Sfn]: Env Revision [XXXX]:
[Sfn]: App Name [XXXX]:
[WARN]: Nested stack has been altered directly! This update may cause unexpected modifications!
[WARN]: Stack name: logstash-development-LogstashCacheCluster-7AUEBUBR73OH. Parameter: EnvShort. Current value: . Expected value: dev (via: "dev")
[Sfn]: Use current value or expected value for EnvShort [current/expected]?: expected
[Sfn]: Env Short [dev]:
[Sfn]: Cache Node Type [XXXX]:
[Sfn]: Cache Parameter Group Name [XXXX]:
[Sfn]: Engine [XXX]:
[Sfn]: Engine Version [XXXX]:
[Sfn]: Notification Topic Arn [XXXX]:
[Sfn]: Num Cache Clusters [XXXX]:
[Sfn]: Security Group Ids [XXXX]:
[Sfn]: Subnet Ids [XXXXX]:
[WARN]: Nested stack has been altered directly! This update may cause unexpected modifications!
[WARN]: Stack name: logstash-development-LogstashCacheCluster-7AUEBUBR73OH. Parameter: ChefVersion. Current value: . Expected value: 12.7.2 (via: "12.7.2")
[Sfn]: Use current value or expected value for ChefVersion [current/expected]?: expected
[Sfn]: Chef Version [12.7.2]:
ERROR: Miasma::Error::ApiError::RequestError: Moved Permanently
```

**Comment by chrisroberts** [comment]
This is generally an issue with the region of the nesting bucket being different than the target region configured for connecting to the CFN API. In the `credentials` section of your configuration you can define the bucket region explicitly. It would look like:

```ruby
...
  credentials do
    provider :aws
    aws_region 'us-west-1'
    aws_bucket_region 'us-west-2'
    ...
```

If that doesn't fix things up, please run it again with `--debug` and toss the stacktrace in here. Thanks!

**Comment by ls-yann-david** [comment]
Nop, same my bucket actually didn't change and that used to work with the same code (Last update of my template is March 25th)

```bash
ERROR: Miasma::Error::ApiError::RequestError: Moved Permanently
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/api.rb:126:in `block in request'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/bogo-0.2.4/lib/bogo/retry.rb:65:in `call'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/bogo-0.2.4/lib/bogo/retry.rb:65:in `run!'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/api.rb:148:in `retryable_request'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/api.rb:123:in `request'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:141:in `bucket_reload'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/models/storage/bucket.rb:32:in `perform_reload'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/model.rb:83:in `reload'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:105:in `bucket_get'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/collection.rb:106:in `perform_get'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/collection.rb:40:in `block in get'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/miasma-0.3.2/lib/miasma/types/collection.rb:39:in `get'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sfn-2.2.0/lib/sfn/command_module/template.rb:287:in `block in process_nested_stack_deep'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:859:in `call'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:859:in `block in stack_template_extractor'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:854:in `each'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:854:in `stack_template_extractor'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:847:in `extract_templates'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/provider/aws.rb:66:in `apply_deep_nesting'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:800:in `apply_nesting'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sfn-2.2.0/lib/sfn/command_module/template.rb:254:in `process_nested_stack_deep'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sfn-2.2.0/lib/sfn/command_module/template.rb:189:in `load_template_file'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sfn-2.2.0/lib/sfn/command/update.rb:49:in `execute!'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sfn-2.2.0/bin/sfn:56:in `block (4 levels) in <top (required)>'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `call'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:48:in `define'
/Users/yann.david/.rvm/gems/ruby-2.2.1/gems/sfn-2.2.0/bin/sfn:18:in `<top (required)>'
/Users/yann.david/.rvm/gems/ruby-2.2.1/bin/sfn:23:in `load'
/Users/yann.david/.rvm/gems/ruby-2.2.1/bin/sfn:23:in `<main>'
/Users/yann.david/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/yann.david/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by chrisroberts** [comment]
The stacktrace is pointing to the issue being with the template upload to the bucket, and a 301 error on the bucket is generally indicative of the wrong region being configured. Can you validate your currently configured region:

```
$ sfn conf | grep aws_region
```

matches the region the `sfn-dev` bucket was created in? You can check the region either via the web UI or using the aws cli:

```
$ aws s3api get-bucket-location --bucket sfn-dev
```

**Comment by ls-yann-david** [comment]
I'm such a retard -.- The bucket is not `sfn-dev` but `dev-sfn`! Sorry for wasting your time...

I realized that when I got this:

```bash
⇒  aws s3api get-bucket-location --bucket sfn-dev

A client error (AccessDenied) occurred when calling the GetBucketLocation operation: Access Denied
```

**Comment by chrisroberts** [comment]
No worries at all. Glad you got it sorted out.

Cheers!
