### ISSUE TITLE
sfn update undefined method dump

### ISSUE THREAD

**Issue by runningman84** [sparkleformation/sfn#223]
I got this error during an update:
```
 sfn update DEV-SHOP-DEPLOY-a  --file out/demo_shop_deploy_a.json --apply-stack DEV-VPC --apply-stack DEV-BASE --apply-stack DEV-DNS --apply-stack DEV-SHOP-BASE-a --apply-stack DEV-SHOP-BACKEND-a --apply-stack DEV-SHOP-FRONTEND-a --no-processing
[Sfn]: SparkleFormation: update
[Sfn]:   -> Name: DEV-SHOP-DEPLOY-a Path: out/demo_shop_deploy_a.json
[Sfn]: Stack runtime parameters:
[Sfn]: Chef Bucket [dev-base-chefbucket-xxxxxxxxxxxx]: 
[Sfn]: Chef Env [dev]: 
[Sfn]: Chef Org [demo-cloud-dev]: 
[Sfn]: Chef Server Url [https://ec2-xxxxxxxxxx.eu-central-1.compute.amazonaws.com]: 
[Sfn]: Chef Version [12]: 
[Sfn]: Code Deploy App Name [ShopDeployApp]: 
[Sfn]: Code Deploy Group [ShopDeployGroupWeb]: 
[Sfn]: Code Deploy Group Admin [ShopDeployGroupAdmin]: 
[Sfn]: Code Deploy Group Db [ShopDeployGroupDb]: 
[Sfn]: Shop Backend a Stack Name [DEV-SHOP-BACKEND-a]: 
[Sfn]: Shop Frontend a Asg Id [DEV-SHOP-FRONTEND-a-ShdemorontendaAutoScalingGroup-xxxxxxxxxxxx]: 
[Sfn]: Software Bucket [dev-shop-base-a-softwarebucket-xxxxxxxxx]: 
[ERROR]: Unexpected error when generating plan information: NoMethodError - undefined method `dump' for #<Hash:0x000000014296d0>
[Sfn]: Continue with stack update? (Y/N): y
[Sfn]: Events for Stack: DEV-SHOP-DEPLOY-a
```

**Comment by chrisroberts** [comment]
Hi! Can you provide the output of the update with the `--debug` flag added? Thanks!

**Comment by runningman84** [comment]
yes here you go:
```
[ERROR]: Unexpected error when generating plan information: NoMethodError - undefined method `dump' for #<Hash:0x00000001825f90>
[DEBUG]: NoMethodError: undefined method `dump' for #<Hash:0x00000001825f90>
/home/user/.chefdk/gem/ruby/2.1.0/gems/sfn-3.0.18/lib/sfn/command/update.rb:93:in `execute!'
/home/user/.chefdk/gem/ruby/2.1.0/gems/sfn-3.0.18/bin/sfn:52:in `block (4 levels) in <top (required)>'
/home/user/.chefdk/gem/ruby/2.1.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `call'
/home/user/.chefdk/gem/ruby/2.1.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/home/user/.chefdk/gem/ruby/2.1.0/gems/bogo-cli-0.2.6/lib/bogo-cli/setup.rb:48:in `define'
/home/user/.chefdk/gem/ruby/2.1.0/gems/sfn-3.0.18/bin/sfn:14:in `<top (required)>'
/home/user/.chefdk/gem/ruby/2.1.0/bin/sfn:22:in `load'
/home/user/.chefdk/gem/ruby/2.1.0/bin/sfn:22:in `<main>'
```

**Comment by chrisroberts** [comment]
Looks like I need to toss a check in for input type (so it doesn't try and dump when already a hash). Disabling the plan will allow it to continue: --no-plan.
