### ISSUE TITLE
Invalid URI failure during AWS connection

### ISSUE THREAD

**Issue by ckuttruff** [sparkleformation/sfn#231]
Getting the following error when running `bundle exec sfn list`:
```
slackz $ be sfn list --debug
I, [2016-12-07T20:22:51.081310 #12377]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x005643058f6198>)
.amazonaws.com/alidURIError: bad URI(is not URI?): https://cloudformation.us-west-2
/home/slackz/.rbenv/versions/2.3.2/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split'
/home/slackz/.rbenv/versions/2.3.2/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
/home/slackz/.rbenv/versions/2.3.2/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
```

Running sfn version `3.0.18`.  The really odd thing is that sfn is working fine in a different project directory.  AWS environment variables are set and my `.sfn` is very simple (barely modified from the generate command).  Closely followed docs and cannot seem to find any difference with my previous (working) project or what the issue is.  The new project specifies us-west-2 for region as the only difference, but I tested with us-east-1 with the same results.

Thanks in advance!

Any ideas about what I'm doing wrong here?

**Comment by ckuttruff** [comment]
nevermind... this had to do with an underlying configuration failure. All sorted now
