### ISSUE TITLE
Azure and event polling

### ISSUE THREAD

**Issue by AntoineBro** [sparkleformation/sfn#244]
Hi , 

Is the event polling behavior supported with AZURE ?

Without  "--no-poll"  **sfn create** always fail : 

```
$ sfn create sparkle-guide-compute --file compute --debug

[DEBUG]: Initial compile parameters - {}
[DEBUG]: Merged compile parameters - {}
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: sparkle-guide-compute
[Sfn]: Stack runtime parameters: - template: sparkle-guide-compute
[Sfn]: storage Account Name [sparklestor01]: sparklestoragetest
[Sfn]: storage Container Name [vhd]: vhd2
[Sfn]: sparkle Image Id [14.04.2-LTS]:
[Sfn]: sparkle Flavor [Standard_D1]:
[Sfn]: glitzerstern Image Id [14.04.2-LTS]:
[Sfn]: glitzerstern Flavor [Standard_D1]:
[Sfn]: Events for Stack: sparkle-guide-compute
I, [2017-02-17T15:18:13.954706 #44719]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x007ff45c083470>)
I, [2017-02-17T15:18:14.509664 #44719]  INFO -- : Stack list has been updated from upstream and cached locally
Time                 Resource Logical Id   Resource Status      Resource Status Reason
ERROR: NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:80:in `block in get_events'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:65:in `map'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:65:in `get_events'
/.rvm/gems/ruby-2.3.0@global/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:35:in `method_missing'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:24:in `block (3 levels) in execute!'
/.rvm/gems/ruby-2.3.0@global/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:56:in `table'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:23:in `block (2 levels) in execute!'
/.rvm/gems/ruby-2.3.0@global/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `instance_exec'
/.rvm/gems/ruby-2.3.0@global/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `display'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:49:in `block in execute!'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/events.rb:21:in `execute!'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command_module/base.rb:129:in `poll_stack'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/create.rb:66:in `block in execute!'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/lib/sfn/command/create.rb:63:in `execute!'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/bin/sfn:52:in `block (4 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@global/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/.rvm/gems/ruby-2.3.0@global/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/.rvm/gems/ruby-2.3.0@global/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/.rvm/gems/ruby-2.3.0@global/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/.rvm/gems/ruby-2.3.0@global/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/.rvm/gems/ruby-2.3.0@global/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/.rvm/gems/ruby-2.3.0@global/gems/sfn-3.0.22/bin/sfn:14:in `<top (required)>'
/.rvm/rubies/ruby-2.3.0/bin/sfn:23:in `load'
/.rvm/rubies/ruby-2.3.0/bin/sfn:23:in `<main>'
/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

I get the same kind of  error for  **sfn update** and **sfn destroy**

**sfn events** however works fine.

**Comment by kabakakao** [comment]
From Time to Time we have the same error on creating AWS Nested Stacks. I will try the Quick-Fix of gramosbr.
Thanks for that
