### ISSUE TITLE
provider heat vs. open_stack 

### ISSUE THREAD

**Issue by pesimon** [sparkleformation/sfn#245]
Hi, 

Following the [Getting started Guide](http://www.sparkleformation.io/docs/guides/getting-started.html#create-a-template) for HEAT I wasn't able to get it working. 

In `.sfn` setting ` provider :open_stack`  with open_stack_* configs set, makes `sfn list` working. 

But following the example with `:provider => :heat` in sparkle_formation template, can't find the template:   
```
DEBUG=true bundle exec sfn print --file sparkleformation/compute.rb
ERROR: SparkleFormation::Error::NotFound::Template: Failed to locate item named: `/Users/t_peters/w/oa/puppet-openstack/os/sparkleformation/compute.rb`
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/sparkle_formation-3.0.14/lib/sparkle_formation/sparkle_collection.rb:183:in `get'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/sfn-3.0.22/lib/sfn/command_module/template.rb:498:in `set_paths_and_discover_file!'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/sfn-3.0.22/lib/sfn/command_module/template.rb:157:in `load_template_file'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/sfn-3.0.22/lib/sfn/command/print.rb:16:in `execute!'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/sfn-3.0.22/bin/sfn:52:in `block (4 levels) in <top (required)>'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/Users/t_peters/.rvm/gems/ruby-2.3.3/gems/sfn-3.0.22/bin/sfn:14:in `<top (required)>'
/Users/t_peters/.rvm/gems/ruby-2.3.3/bin/sfn:22:in `load'
/Users/t_peters/.rvm/gems/ruby-2.3.3/bin/sfn:22:in `<main>'
/Users/t_peters/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/t_peters/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

```

Setting `:provider => :open_stack` fails with

```
bundle exec sfn print --file sparkleformation/compute.rb
ERROR: RuntimeError: Failed to locate requested dynamic block for insertion: nova_server (valid: )
```

Versions:
```
$ ruby -v                            
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
$ bundle list                   
Gems included by the bundle:
  * addressable (2.5.0)
  * attribute_struct (0.3.4)
  * bogo (0.2.8)
  * bogo-cli (0.2.12)
  * bogo-config (0.2.2)
  * bogo-ui (0.1.24)
  * bundler (1.13.6)
  * colored (1.2)
  * command_line_reporter (3.3.6)
  * domain_name (0.5.20170223)
  * graph (2.8.2)
  * hashdiff (0.2.3)
  * hashie (3.5.5)
  * http (1.0.4)
  * http-cookie (1.0.3)
  * http-form_data (1.0.1)
  * http_parser.rb (0.6.0)
  * jmespath (1.3.1)
  * miasma (0.3.2)
  * miasma-aws (0.3.6)
  * miasma-azure (0.1.4)
  * miasma-google (0.1.0)
  * miasma-open-stack (0.1.4)
  * miasma-rackspace (0.1.2)
  * miasma-terraform (0.1.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * multi_json (1.12.1)
  * multi_xml (0.6.0)
  * net-ssh (4.1.0)
  * paint (2.0.0)
  * public_suffix (2.0.5)
  * sfn (3.0.22)
  * slop (3.6.0)
  * sparkle_formation (3.0.14)
  * unf (0.1.4)
  * unf_ext (0.0.7.2)
  * xml-simple (1.1.5)
```

**Comment by chrisroberts** [comment]
Looks like I have a bug in the guide. The provider setting in the template should match the provider, not the provider service. That means it should be:

```
SparkleFormation.new(:template_name, :provider => :open_stack)
```

When defining dynamics, components, etc., you must set the provider as well for them to be available. If the provider is unset, it defaults to `:aws`. More information here:

http://www.sparkleformation.io/docs/sparkle_formation/provider-restrictions.html

Thanks for creating the issue! I'll get the guide updated.
