### ISSUE TITLE
sfn create produces undefined method error

### ISSUE THREAD

**Issue by runningman84** [sparkleformation/sfn#246]
How can we fix this?
```
cloud-sparkle-formation$ sfn create DEV-BASE  --file out/opf/my_base.json --apply-stack DEV-VPC --no-processing --debug
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: DEV-BASE
I, [2017-03-14T15:32:58.724283 #25903]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x00560434fee230>)
I, [2017-03-14T15:33:01.433257 #25903]  INFO -- : Stack list has been updated from upstream and cached locally
ERROR: NoMethodError: undefined method `root' for #<Hash:0x00560435ae3938>
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.22/lib/sfn/command_module/stack.rb:243:in `block in populate_parameters!'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.22/lib/sfn/command_module/stack.rb:242:in `each'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.22/lib/sfn/command_module/stack.rb:242:in `populate_parameters!'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.22/lib/sfn/command/create.rb:52:in `execute!'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.22/bin/sfn:52:in `block (4 levels) in <top (required)>'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.22/bin/sfn:14:in `<top (required)>'
/home/user/.rbenv/versions/2.3.1/bin/sfn:23:in `load'
/home/user/.rbenv/versions/2.3.1/bin/sfn:23:in `<main>'
```

**Comment by sing102** [comment]
I am also facing same issue. 
My sfn cli version is 3.0.22.

**Comment by rajaws2015** [comment]
Hi,

Actually the issue is with the version of sfn 3.0.22. 
The solution is :: uninstall the version 3.0.22 and Install the version of sfn 3.0.20.

It worked for me.

**Comment by sing102** [comment]
Yes. It worked. :)
