### ISSUE TITLE
ERROR: Miasma::Error::OrchestrationError::InvalidTemplate

### ISSUE THREAD

**Issue by webframp** [sparkleformation/sfn#274]
Seeing this error when attempting to validate a template with : `sfn validate`. 

This seems to happen with json or sfn templates and where this is happening does not have locally stored aws credentials but has an IAM Role applied to the node which should allow the sdk to discover the credentials.

```
[Sfn]: Template Validation (aws):  templatetest.json
ERROR: Miasma::Error::OrchestrationError::InvalidTemplate: The security token included in the request is invalid.
/usr/local/bundle/gems/miasma-0.3.2/lib/miasma/models/orchestration/stack.rb:133:in `perform_template_validate'
/usr/local/bundle/gems/miasma-0.3.2/lib/miasma/models/orchestration/stack.rb:75:in `validate'
/usr/local/bundle/gems/sfn-3.0.30/lib/sfn/command/validate.rb:61:in `block in validate_stack'
/usr/local/bundle/gems/sfn-3.0.30/lib/sfn/command_module/callbacks.rb:20:in `api_action!'
/usr/local/bundle/gems/sfn-3.0.30/lib/sfn/command/validate.rb:60:in `validate_stack'
/usr/local/bundle/gems/sfn-3.0.30/lib/sfn/command/validate.rb:24:in `execute!'
/usr/local/bundle/gems/sfn-3.0.30/bin/sfn:52:in `block (4 levels) in <top (required)>'
/usr/local/bundle/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/usr/local/bundle/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/usr/local/bundle/gems/sfn-3.0.30/bin/sfn:14:in `<top (required)>'
/usr/local/bundle/bin/sfn:23:in `load'
/usr/local/bundle/bin/sfn:23:in `<main>'
[Sfn]: Validating: templatetest
[Sfn]:   -> INVALID
[FATAL]: The security token included in the request is invalid.
```

**Comment by chrisroberts** [comment]
@webframp did setting `aws_iam_instance_profile` in the .sfn credentials file fix this up?

**Comment by webframp** [comment]
@chrisroberts Yes it did, sorry for delay
