### ISSUE TITLE
Stack Plan Fails with undefined method 'to_sym'

### ISSUE THREAD

**Issue by slyness** [sparkleformation/sfn#303]
Hi, I've never got this before but a particular stack just failed to generate a Plan with the following error.

The same stack is able to generate and provide change information using `sfn diff` 

but the below happened when trying to generate the plan during `sfn update`

```
D, [2019-12-11T10:57:43.907725 #53857] DEBUG -- miasma.aws.signature4: generating signature for `"AWS4-HMAC-SHA256\n20191211T185743Z\n20191211/us-west-2/cloudformation/aws4_request\n64793ceecd27d1410795253b60b32ea5f7e503ed0844e1ea9ea397d6e6067e01"`
D, [2019-12-11T10:57:43.907762 #53857] DEBUG -- miasma.aws.hmac: signing data `"20191211"`
D, [2019-12-11T10:57:43.907787 #53857] DEBUG -- miasma.aws.hmac: using key override for signing
D, [2019-12-11T10:57:43.907823 #53857] DEBUG -- miasma.aws.hmac: signing data `"us-west-2"`
D, [2019-12-11T10:57:43.907847 #53857] DEBUG -- miasma.aws.hmac: using key override for signing
D, [2019-12-11T10:57:43.907881 #53857] DEBUG -- miasma.aws.hmac: signing data `"cloudformation"`
D, [2019-12-11T10:57:43.907905 #53857] DEBUG -- miasma.aws.hmac: using key override for signing
D, [2019-12-11T10:57:43.907939 #53857] DEBUG -- miasma.aws.hmac: signing data `"aws4_request"`
D, [2019-12-11T10:57:43.907962 #53857] DEBUG -- miasma.aws.hmac: using key override for signing
D, [2019-12-11T10:57:43.908000 #53857] DEBUG -- miasma.aws.hmac: hex signing data `"AWS4-HMAC-SHA256\n20191211T185743Z\n20191211/us-west-2/cloudformation/aws4_request\n64793ceecd27d1410795253b60b32ea5f7e503ed0844e1ea9ea397d6e6067e01"`
D, [2019-12-11T10:57:43.908038 #53857] DEBUG -- miasma.aws.signature4: generated signature `"8a3a7dbcae4cd68772bd37f2009aaa17d3f2e49f94f46aaf696c0bddf143d8de"`
D, [2019-12-11T10:57:44.540587 #53857] DEBUG -- miasma.aws.orchestration: extracting HTTP response body
D, [2019-12-11T10:57:44.956796 #53857] DEBUG -- miasma.aws.orchestration: unpacking HTTP response body using XML
[ERROR]: Unexpected error when generating plan information: NoMethodError - undefined method `to_sym' for ["interrupt", "none"]:Array
Did you mean?  to_s
               to_set
[DEBUG]: NoMethodError: undefined method `to_sym' for ["interrupt", "none"]:Array
Did you mean?  to_s
               to_set
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/planner/aws.rb:588:in `register_diff'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/planner/aws.rb:447:in `block in run_stack_diff'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/planner/aws.rb:446:in `each'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/planner/aws.rb:446:in `run_stack_diff'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/planner/aws.rb:374:in `plan_stack'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/planner/aws.rb:252:in `generate_plan'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/lib/sfn/command/update.rb:98:in `execute!'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/bin/sfn:52:in `block (4 levels) in <top (required)>'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:50:in `define'
/Users/abaer/.rvm/gems/ruby-2.6.3/gems/sfn-3.1.6/bin/sfn:14:in `<top (required)>'
/Users/abaer/.rvm/gems/ruby-2.6.3/bin/sfn:23:in `load'
/Users/abaer/.rvm/gems/ruby-2.6.3/bin/sfn:23:in `<main>'
/Users/abaer/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/abaer/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
[Sfn]: Continue with stack update? (Y/N): 
```

**Comment by gramosbr** [comment]
+1
