### ISSUE TITLE
knife cloudformation create fails

### ISSUE THREAD

**Issue by LouTheBrew** [sparkleformation/sfn#84]
Hello, any help appreciated.

I am using knife cloudformation create ChefTest -VV and receiving this stack error

```
(eval):24:in `dynamic': undefined method `push' for nil:NilClass (NoMethodError)
	from /Users/ldesiqueira/.work/LouTheBrew/eldus/sparkleformations/lou-sparkles/dynamics/chef_client.rb:1:in `block (3 levels) in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:257:in `instance_eval'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:257:in `block (3 levels) in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:249:in `glob'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:249:in `block (2 levels) in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:248:in `tap'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:248:in `block in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/bogo-0.1.30/lib/bogo/memoization.rb:60:in `memoize'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle.rb:247:in `templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle_collection.rb:104:in `block (3 levels) in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle_collection.rb:103:in `each'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle_collection.rb:103:in `block (2 levels) in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle_collection.rb:102:in `tap'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle_collection.rb:102:in `block in templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/bogo-0.1.30/lib/bogo/memoization.rb:60:in `memoize'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sparkle_formation-1.1.10/lib/sparkle_formation/sparkle_collection.rb:101:in `templates'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sfn-1.1.14/lib/sfn/command_module/template.rb:344:in `prompt_for_template'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sfn-1.1.14/lib/sfn/command_module/template.rb:314:in `set_paths_and_discover_file!'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sfn-1.1.14/lib/sfn/command_module/template.rb:117:in `load_template_file'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sfn-1.1.14/lib/sfn/command/create.rb:20:in `execute!'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/sfn-1.1.14/lib/chef/knife/knife_plugin_seed.rb:79:in `run'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/bin/knife:23:in `load'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/bin/knife:23:in `<main>'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ldesiqueira/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

I can use SparkleFormation to parse my template to json successfully.  So compiling works.  It's just the knife command to create that does not.  I can successfully execute knife cloudformation list and I have admin permissions on my AWS profile.

**Comment by LouTheBrew** [comment]
Resolved and was an error within my own sparkleformation pack.
